[build]
  command = "pnpm run generate"
  publish = "/dist/"

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  force = true

[[headers]]
for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "http://localhost:3000"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"