[build]
  command = "pnpm run generate"
  publish = "/dist/"

[[headers]]
for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "localhost:3000"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"